name: 'Wait / Sleep Action'
description: 'Github actions to wait / sleep during a job execution ⏱'

inputs:
  time:
    description: 'A number (integer) followed by s for seconds, m for minutes, h for hours, d for days.'
    required: true

runs:
  using: "composite"
  steps:
    - name:
      run: |
        echo "Waiting for ${{ inputs.time }}... ⏱"
        if [[ $OSTYPE == 'darwin'* ]]; then 
          echo 'macOS'
          PATH=$PATH/bin
          INPUT=${{ inputs.time }}
          if [[ ${{ inputs.time }} == *"s"* ]]; then
            sleep ${{ inputs.time }}
          elif [[ ${{ inputs.time }} == *"m"* ]]; then
            DURATION="${INPUT/"m"/}"
            DURATION="$(expr $DURATION \* 60)"
            sleep $DURATION
          elif [[ ${{ inputs.time }} == *"h"* ]]; then
            DURATION="${INPUT/"h"/}"
            DURATION="$(expr $DURATION \* 60 \* 60)"
            sleep $DURATION
          elif [[ ${{ inputs.time }} == *"d"* ]]; then
            DURATION="${INPUT/"d"/}"
            DURATION="$(expr $DURATION \* 60 \* 60 \* 24)"
            sleep $DURATION
          else
            sleep ${{ inputs.time }}
          fi
        else
          sleep ${{ inputs.time }}
        fi
        echo "Time to get-going! 🚀"
      shell: bash

branding:
  icon: clock
  color: black