name: 'Wait / Sleep Action'
description: 'Github actions to wait / sleep during a job execution ⏱'

inputs:
  time:
    description: 'A number (integer) followed by s for seconds, m for minutes, h for hours, d for days.'
    required: true

runs:
  using: "composite"
  steps:
    - name:
      run: |
        echo "Waiting for ${{ inputs.time }}... ⏱"
        if [[ $OSTYPE == 'darwin'* ]]; then 
          echo 'macOS'
          PATH=$PATH/bin
          if [[ ${{ inputs.time }} == *"s"* ]]; then
            sleep ${{ inputs.time }}
          elif [[ ${{ inputs.time }} == *"m"* ]]; then
            duration=$(echo "${${{ inputs.time }}/m/""}")
            duration=$($duration * 60)
            echo $duration
            sleep $duration
          # elif [[ ${{ inputs.time }} == *"h"* ]]; then
          #   duration=$(echo "${${{ inputs.time }}/h/""}")
          #   duration=$($duration * 60 * 60)
          #   echo $duration
          #   sleep $duration
          # elif [[ ${{ inputs.time }} == *"d"* ]]; then
          #   duration=$(echo "${${{ inputs.time }}/d/""}")
          #   duration=$($duration * 60 * 60 * 24)
          #   echo $duration
          #   sleep $duration
          else
            sleep ${{ inputs.time }}
          fi
        else
          sleep ${{ inputs.time }}
        fi
        echo "Time to get-going! 🚀"
      shell: bash

branding:
  icon: clock
  color: black